# CREATED BY BERRABE
# https://github.com/berrabe/docker-php-framework
---
version: '2.2'


x-resource: &resource
    restart: unless-stopped
    cpus: 1
    mem_limit: 300M
    memswap_limit: 300M


x-code-dir: &code-dir
    "./code:/code"



services:
    nginx:
        << : *resource
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - *code-dir
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php


    mariaDB:
        << : *resource
        image: yobasystems/alpine-mariadb
        volumes:
            - ./db:/var/lib/mysql:rw
        depends_on:
            - nginx
        environment:
            MYSQL_ROOT_PASSWORD: berrabe


    php:
        << : *resource
        build: .
        volumes:
            - *code-dir


    phpmyadmin:
        << : *resource
        image: mhzawadi/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariaDB
        depends_on:
            - mariaDB
